name: CI/CD Aula

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o codigo
      uses: actions/checkout@v2

    - name: Usando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Instalando as dependencias
      run: npm install

    - name: Rodando os testes
      run: npm run test
